---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodeport-controller
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeport-controller
rules:
- apiGroups: [""]
  resources: ["services", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["custom.io"]
  resources: ["nodeports"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodeport-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nodeport-controller
subjects:
- kind: ServiceAccount
  name: nodeport-controller
  namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-controller
  namespace: kube-system
  labels:
    app: nodeport-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeport-controller
  template:
    metadata:
      labels:
        app: nodeport-controller
    spec:
      serviceAccountName: nodeport-controller
      containers:
      - name: nodeport-controller
        image: virsuryaircas/nodeport-controller:v1
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
