apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodeports.custom.io
spec:
  group: custom.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              serviceName:
                type: string
              namespace:
                type: string
                default: "default"
          status:
            type: object
            properties:
              nodeIP:
                type: string
              clusterIP:
                type: string
              ports:
                type: string
              age:
                type: string
    additionalPrinterColumns:
    - name: NODE-IP
      type: string
      description: Clickable URL for Node IP and Port
      jsonPath: .status.nodeIP
    - name: CLUSTER-IP
      type: string
      description: Cluster IP
      jsonPath: .status.clusterIP
    - name: PORT(S)
      type: string
      description: Service ports
      jsonPath: .status.ports
    - name: AGE
      type: string
      description: Age of the service
      jsonPath: .status.age
  scope: Namespaced
  names:
    plural: nodeports
    singular: nodeport
    kind: NodePort
    shortNames:
    - np
